### ISSUE TITLE
RealTimeFilter crashed.

### ISSUE THREAD

**Issue by brandy2015** [zhangao0086/iOS-CoreImage-Swift#2]
Debug shows " fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) "

Then Thread points to "let deviceInput = AVCaptureDeviceInput.deviceInputWithDevice(captureDevice, error: nil) as AVCaptureDeviceInput
"

**Comment by zhangao0086** [comment]
Did you use Xcode 6.3 Beta?

**Comment by zhangao0086** [comment]
Simulators?
